### ISSUE TITLE
Conflict with blip node

### ISSUE THREAD

**Issue by liangkun43** [hhhzzyang/Comfyui_Lama#1]
Thank you very much for your work, but when I installed this node and used the example workflow, an error occurred with "comfy_clip_blip_node". When I uninstalled this node, "comfy_clip_blip_node" worked fine.The error was also received using the blip node in "was-node-suite-comfyui".
![微信截图_20231005173436](https://github.com/hhhzzyang/Comfyui_Lama/assets/135417715/f9573d0d-7536-4790-8956-cd3d170ab48c)
![微信截图_20231005174117](https://github.com/hhhzzyang/Comfyui_Lama/assets/135417715/e5702e9c-1218-4ae0-9a1e-35782f33cb2f)
![微信截图_20231005113633](https://github.com/hhhzzyang/Comfyui_Lama/assets/135417715/6c6dcf13-4ba4-4669-a29a-8c343fc6d311)

**Comment by hhhzzyang** [comment]
This error is thrown inside blip node. And there has been same [issue](https://github.com/paulo-coronado/comfy_clip_blip_node/pull/3) in blip node project. However, I only change the module "model" to be imported with relative path form. The example workflow works.
As shown in first picture, the lama nodes group works well. And I add the following blip and sd nodes to further make blurred area after lama nodes to be more clear

**Comment by liangkun43** [comment]
Thanks!
