### ISSUE TITLE
Error: too many values to unpack

### ISSUE THREAD

**Issue by cian0** [hhhzzyang/Comfyui_Lama#4]
too many values to unpack (expected 4)

File "/media/ian/My Book/ComfyUI/execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/media/ian/My Book/ComfyUI/execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/media/ian/My Book/ComfyUI/execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/media/ian/My Book/ComfyUI/custom_nodes/Comfyui_Lama/LamaRemove.py", line 74, in lama_remove
img_inpainted = inpaint_img_with_lama(
File "/media/ian/My Book/ComfyUI/custom_nodes/Comfyui_Lama/LamaRemove.py", line 38, in inpaint_img_with_lama
batch['mask'] = pad_tensor_to_modulo(batch['mask'], mod)
File "/media/ian/My Book/ComfyUI/custom_nodes/Comfyui_Lama/saicinpainting/evaluation/data.py", line 37, in pad_tensor_to_modulo
batch_size, channels, height, width = img.shape

**Comment by cian0** [comment]
actually this worked when I used the dliate mask node, maybe it should be in the documentation?

**Comment by rehovits** [comment]
> actually this worked when I used the dliate mask node, maybe it should be in the documentation?

What is the dliate maks node? Can you share the link?

**Comment by cian0** [comment]
> > actually this worked when I used the dliate mask node, maybe it should be in the documentation?
> 
> What is the dliate maks node? Can you share the link?

https://github.com/hhhzzyang/Comfyui_Lama/blob/main/lamaworkfolw.json

The one from the default workflow (i believe from impact pack)

**Comment by lldacing** [comment]
![image](https://github.com/hhhzzyang/Comfyui_Lama/assets/43737696/75a01e2e-0fbf-4b33-9d93-515edcfaece1)
@cian0

**Comment by davedaverave** [comment]
I still got this issues even with dilate mask...

**Comment by lldacing** [comment]
可以把LamaRemove.py第35行的
batch['mask'] = mask[None, None]
修改为
batch['mask'] = mask.reshape((-1, 1, mask.shape[-2], mask.shape[-1]))
@davedaverave

**Comment by cian0** [comment]
> 可以把LamaRemove.py第35行的
> batch['mask'] = mask[None, None]
> 修改为
> batch['mask'] = mask.reshape((-1, 1, mask.shape[-2], mask.shape[-1]))
> @davedaverave

This worked for me thanks!
