### ISSUE TITLE
Load failure

### ISSUE THREAD

**Issue by bubbl000** [hhhzzyang/Comfyui_Lama#7]
![image](https://github.com/hhhzzyang/Comfyui_Lama/assets/108770692/5f324f80-5686-4c9d-8903-5ff83bd55e6a)
How to solve this situation, loading several times is a failure

**Comment by thosupercop2** [comment]
i have the exact same problem. 
Downloaded cpkt into custom_node/comfy_Lama/models though!

**Comment by GaryLiujia** [comment]
我也有完全相同的问题，始终解决不了
